NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: tlscacerts/tls-ca.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: tlscacerts/tls-ca.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: tlscacerts/tls-ca.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: tlscacerts/tls-ca.pem
    OrganizationalUnitIdentifier: orderer