apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-orgx-peer1
  labels:
    volume: orgx-peer1
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /run/media/pedromn35/disk2-home/projects/block-alten/config/storage/orgx-peer1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - archlinux
