apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-orgy-peer1
  labels:
    volume: orgy-peer1
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/c/Users/psousaesilva/Documents/blockchain-identity-project/config/storage/orgy-peer1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 0324123g-alten
